# Generated by Django 5.0.1 on 2024-02-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracking_system', '0003_alter_project_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='date_closed',
        ),
        migrations.AddField(
            model_name='sprint',
            name='labels',
            field=models.ManyToManyField(related_name='sprints', to='issue_tracking_system.label'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
