# Generated by Django 5.0.1 on 2024-02-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracking_system', '0004_remove_sprint_date_closed_sprint_labels_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='label',
            old_name='name',
            new_name='label',
        ),
        migrations.AlterField(
            model_name='issue',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='issues', to='issue_tracking_system.label'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='sprints', to='issue_tracking_system.label'),
        ),
    ]
