# Generated by Django 5.0.1 on 2024-02-09 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracking_system', '0006_label_created_at_label_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sprint',
            old_name='date_created',
            new_name='created_at',
        ),
    ]
