# Generated by Django 5.0.1 on 2024-02-09 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracking_system', '0007_rename_date_created_sprint_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='description',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='project',
        ),
    ]
