# Generated by Django 5.0.1 on 2024-02-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracking_system', '0008_remove_issue_description_remove_issue_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='labels',
            field=models.ManyToManyField(blank=True, null=True, related_name='issues', to='issue_tracking_system.label'),
        ),
    ]
