# Generated by Django 5.0.1 on 2024-02-10 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracking_system', '0009_alter_issue_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
