# Generated by Django 5.0.1 on 2024-02-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracking_system', '0010_alter_issue_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
