# Generated by Django 5.0.1 on 2024-02-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracking_system', '0013_alter_userproject_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watcher',
            name='watch_status',
        ),
        migrations.AddField(
            model_name='watcher',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
