# Generated by Django 5.0.1 on 2024-02-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracking_system', '0016_rename_author_comment_user_comment_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='issues', to='issue_tracking_system.label'),
        ),
    ]
